### ISSUE TITLE
streamable-http transport does not work

### ISSUE THREAD

**Issue by roaguirre** [grafana/mcp-grafana#177]
I'm running the MCP server with Docker. Maybe it has not been released yet?

```sh
panic: Invalid transport type: streamable-http. Must be 'stdio' or 'sse'

goroutine 1 [running]:
main.main()
	/app/cmd/mcp-grafana/main.go:137 +0x29c
panic: Invalid transport type: streamable-http. Must be 'stdio' or 'sse'

goroutine 1 [running]:
main.main()
	/app/cmd/mcp-grafana/main.go:137 +0x29c
panic: Invalid transport type: streamable-http. Must be 'stdio' or 'sse'

goroutine 1 [running]:
main.main()
	/app/cmd/mcp-grafana/main.go:137 +0x29c
```

**Comment by sd2k** [comment]
Hi @roaguirre, I'm not sure how often the Docker image is built, it's handled automatically by Docker's MCP image builders. I've just pushed a new tag (`v0.5.0`) so hopefully it will be built soon 👍

**Comment by piyush-bit** [comment]
Hey @sd2k, the issue still persists.
I’ve added 'streamable-http' to the transport flags which were missing —  #179

**Comment by sd2k** [comment]
Thanks for the PR, that will certainly help. Yeah it looks like the Docker image still hasn't been built (https://hub.docker.com/r/mcp/grafana says 10 days ago), I'm not entirely sure what the cadence is for that since it's handled by Docker 😕

**Comment by piyush-bit** [comment]
@sd2k, even though the image has been updated, the issue is still there
wondering what the reason is ..

**Comment by frogshell** [comment]
This was bugging me too.

The MCP registry on DockerHub looks to be populated by [this repo](https://github.com/docker/mcp-registry/) where you can find the [Grafana MCP server](https://github.com/docker/mcp-registry/blob/main/servers/grafana/server.yaml#L15) which is pointing to a specific branch called `c03ca3c387b2cd9b3d8d2fbd56d2a9e6b7b603fb` that does not exist. 

I submitted a pull request to fix it here [#14](https://github.com/docker/mcp-registry/pull/14). 

@sd2k does this seem right?

**Comment by sd2k** [comment]
Hi folks. @frogshell thanks for finding that, I wasn't made aware of where the builds are configured so that is very helpful! The image in the DockerHub _has_ been updated in the past so I assume there was some other process going through and rebuilding from `main` but perhaps that's changed in the last week (since the file you mention was first committed). I'll subscribe to your PR and keep an eye on it.

FYI I'm also in touch with an engineer from Docker regarding building tagged images rather than just `latest`; I'd like all our git tags to end up with tagged Docker images too, with the most recent being tagged as `latest`. Hopefully the Docker folks can implement that for us.

**Comment by SandersAaronD** [comment]
Closing this as resolved by the PR to docker (thank you, @frogshell) and probably opening a different one about trying to get them to build our server with version tags since that's pending and not tracked thus far.

**Comment by nissessenap** [comment]
This actually seemed to have been solved. We can now see the mcp-server in dockerhub https://hub.docker.com/r/grafana/mcp-grafana/tags under grafanas org as well. And it contains tags 🎉 
Fixed in https://github.com/grafana/mcp-grafana/pull/313

**Comment by ChinthapalliNikhithaChandana** [comment]
Using grafana/mcp-grafana:0.7.9 , still seeing

panic: invalid transport type: streamable_http. Must be 'stdio', 'sse' or 'streamable-http'

goroutine 1 [running]:
main.main()
    /app/cmd/mcp-grafana/main.go:367 +0x4f1
Stream closed EOF for grafana-mcp/mcp-grafana-8b6b457d9-hc2mn (mcp-grafana)

**Comment by sd2k** [comment]
@ChinthapalliNikhithaChandana you need to use `streamable-http` not `streamable_http`.

**Comment by ChinthapalliNikhithaChandana** [comment]
> [@ChinthapalliNikhithaChandana](https://github.com/ChinthapalliNikhithaChandana) you need to use `streamable-http` not `streamable_http`.

Thank you
